dist: xenial
addons:
 apt:
  packages:
   enchant
language: python
sudo: false
cache: pip
arch:
 - amd64
 - ppc64le
python:
 - "3.8"
 - "3.7"
 - "3.6"
 - "3.5"
install: pip install tox-travis
script: tox
